version: '3.8'
services:
  react:
    build: .
    command: sh -c 'pnpm install && pnpm start --host'
    environment:
      APP_TITLE: ${APP_TITLE:- Montandon ETL Dashboard}
    volumes:
      - .:/code
    ports:
      - '3000:3000'
