name: monty-web-app-serve

services:
  web-app-serve:
    build:
      context: ../
      target: web-app-serve
    environment:
      APP_TITLE: ${APP_TITLE:- Montandon ETL Dashboard}
      APP_GRAPHQL_ENDPOINT: ${APP_GRAPHQL_ENDPOINT:-http://localhost:8000/graphql/}
      # web-app-serve config
      APPLY_CONFIG__ENABLE_DEBUG: true
    env_file: .env
    ports:
      - '8050:80'
