name: Lint & Build

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_TITLE: ${{ vars.APP_TITLE }}
  GITHUB_WORKFLOW: true

jobs:
  unused:
    name: Find unused things
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run knip
        run: pnpm lint:unused
  lint-js:
    name: Lint JS
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint Javascript
        run: pnpm lint:js
  css-lint:
    name: Lint CSS
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Css Lint
        run: pnpm lint:css
  typecheck:
    name: Typecheck
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint Javascript
        run: pnpm typecheck
  build:
    name: Build
    environment: 'test'
    needs: [lint-js, css-lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.12.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
